[tool.poetry]
name = "flask-checkr"
version = "0.1.0"
description = "Easily validate Flask requests with JSONSchema."
authors = ["Pavel P. <pascaripavel@gmail.com>"]
readme = "README.rst"
repository = "https://github.com/pavelpascari/flask-checkr"
license = "MIT"

[tool.poetry.dependencies]
python = "^2.7"
flask = "^1.1.2"
jsonschema = "^3.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
