[tool.poetry]
name = "wfslib"
version = "0.1.1"
description = "Programming module for wave front data processing"
authors = ["Zoya"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
wfslib = 'entry:main'