[tool.poetry]
name = "pgedl"
version = "0.1.0"
description = ""
authors = ["myyc <myyc@domain.xxx>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.23.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
pgedl = "pgedl.pgedl:run"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
