[tool.poetry]
name = "stripe-repr"
version = "1.0.0"
description = "A monkey-patch library to provide more compact representation for Stripe objects"
readme = "README.md"
homepage = "https://github.com/Doist/stripe-repr"
repository = "https://github.com/Doist/stripe-repr"
authors = ["Doist Developers <dev@doist.com>"]
license = "MIT"
classifiers = [
    "Intended Audience :: Developers",
    ]
include = [
    "CHANGELOG.md"
]

[tool.poetry.dependencies]
python = "^3.8"
stripe = "^2.48.0"

[tool.poetry.dev-dependencies]
pytest = "^5.3.2"
black = "^19.10b0"
flake8 = "^3.7.9"

[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"
